### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by gottwald**
Build was broken with commit 50961ec.

---
name: Pull request
about: Propose changes to the code
title: 'Fix build'
labels: 'v2'
assignees: ''
---

## 1. What does this change do, exactly?

Fix build

## 2. Please link to the relevant issues.

Build seems to be broken by commit 50961ec (#2731)

## 3. Which documentation changes (if any) need to be made because of this PR?

none

## 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [ ] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by mholt** [comment]
What errors are you getting? It builds for me.

**Comment by gottwald** [comment]
Just wanted to try caddy v2 and did the following:

```
 $ git clone -b v2 "https://github.com/caddyserver/caddy.git"
Cloning into 'caddy'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (181/181), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 18416 (delta 101), reused 117 (delta 57), pack-reused 18235
Receiving objects: 100% (18416/18416), 11.00 MiB | 5.71 MiB/s, done.
Resolving deltas: 100% (11215/11215), done.
 $ cd caddy/cmd/caddy/
 $ go build
# github.com/caddyserver/caddy/v2/modules/caddyhttp
../../modules/caddyhttp/server.go:186:8: cp.Active undefined (type *caddytls.ConnectionPolicy has no field or method Active)
```

```
 $ git rev-parse --short HEAD
3ba9e143
```

AFAICS `cp.Active` is really undefined. I'm surprised it builds for you.

**Comment by mholt** [comment]
Well a nil check isn't going to fix the compilation error. :) I'm surprised this works for you. I suspect something else may be wrong with your setup, then.

Going to close this until we can determine anything actionable from it.

**Comment by gottwald** [comment]
I believe you missed that it's not just a nil check. The `Active` method is called on a different struct, one where it exists.
I tried to compile the `v2` branch on 2 different systems now (mac and linux) with the same result: doesn't compile at `3ba9e143` with the above posted message but does compile with this PR.

I can also reporduce it with the official golang docker image:
```
$ mkdir /tmp/caddy-test && cd /tmp/caddy-test

$ git clone -b v2 "https://github.com/caddyserver/caddy.git"
Cloning into 'caddy'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (181/181), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 18416 (delta 101), reused 117 (delta 57), pack-reused 18235
Receiving objects: 100% (18416/18416), 11.00 MiB | 10.69 MiB/s, done.
Resolving deltas: 100% (11215/11215), done.

$ cd caddy 

$ docker run --rm -v "$PWD":/caddy -w /caddy/cmd/caddy -e GO111MODULE=on golang:1.13.0 go build
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/Masterminds/sprig v2.20.0+incompatible
go: downloading github.com/klauspost/compress v1.7.1-0.20190613161414-0b31f265a57b
go: downloading github.com/rs/cors v1.6.0
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading go.starlark.net v0.0.0-20190604130855-6ddc71c0ba77
go: downloading golang.org/x/net v0.0.0-20190603091049-60506f45cf65
go: downloading github.com/mholt/certmagic v0.6.2
go: downloading github.com/andybalholm/brotli v0.0.0-20190704151324-71eb68cc467c
go: downloading github.com/go-acme/lego v2.6.0+incompatible
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/mitchellh/go-ps v0.0.0-20170309133038-4fdf99ab2936
go: extracting github.com/rs/cors v1.6.0
go: extracting github.com/Masterminds/sprig v2.20.0+incompatible
go: downloading github.com/Masterminds/goutils v1.1.0
go: downloading github.com/klauspost/cpuid v1.2.1
go: extracting github.com/mholt/certmagic v0.6.2
go: extracting github.com/mitchellh/go-ps v0.0.0-20170309133038-4fdf99ab2936
go: extracting go.starlark.net v0.0.0-20190604130855-6ddc71c0ba77
go: extracting github.com/Masterminds/goutils v1.1.0
go: extracting github.com/russross/blackfriday/v2 v2.0.1
go: extracting github.com/klauspost/cpuid v1.2.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/huandu/xstrings v1.2.0
go: extracting github.com/andybalholm/brotli v0.0.0-20190704151324-71eb68cc467c
go: downloading github.com/imdario/mergo v0.3.7
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/google/uuid v1.1.1
go: extracting github.com/huandu/xstrings v1.2.0
go: extracting github.com/go-acme/lego v2.6.0+incompatible
go: extracting github.com/google/uuid v1.1.1
go: extracting github.com/imdario/mergo v0.3.7
go: downloading github.com/Masterminds/semver v1.4.2
go: downloading github.com/golang/gddo v0.0.0-20190419222130-af0f2af80721
go: extracting github.com/Masterminds/semver v1.4.2
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: extracting golang.org/x/net v0.0.0-20190603091049-60506f45cf65
go: downloading github.com/starlight-go/starlight v0.0.0-20181207205707-b06f321544f3
go: downloading github.com/cenkalti/backoff v2.1.1+incompatible
go: downloading github.com/miekg/dns v1.1.3
go: downloading gopkg.in/square/go-jose.v2 v2.2.2
go: extracting github.com/golang/gddo v0.0.0-20190419222130-af0f2af80721
go: extracting github.com/starlight-go/starlight v0.0.0-20181207205707-b06f321544f3
go: extracting github.com/cenkalti/backoff v2.1.1+incompatible
go: extracting github.com/miekg/dns v1.1.3
go: extracting gopkg.in/square/go-jose.v2 v2.2.2
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: extracting golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading golang.org/x/text v0.3.0
go: extracting github.com/klauspost/compress v1.7.1-0.20190613161414-0b31f265a57b
go: extracting golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: extracting golang.org/x/text v0.3.0
go: finding github.com/andybalholm/brotli v0.0.0-20190704151324-71eb68cc467c
go: finding github.com/klauspost/compress v1.7.1-0.20190613161414-0b31f265a57b
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding github.com/Masterminds/sprig v2.20.0+incompatible
go: finding github.com/mholt/certmagic v0.6.2
go: finding github.com/rs/cors v1.6.0
go: finding golang.org/x/net v0.0.0-20190603091049-60506f45cf65
go: finding github.com/mitchellh/go-ps v0.0.0-20170309133038-4fdf99ab2936
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding go.starlark.net v0.0.0-20190604130855-6ddc71c0ba77
go: finding github.com/go-acme/lego v2.6.0+incompatible
go: finding github.com/golang/gddo v0.0.0-20190419222130-af0f2af80721
go: finding github.com/starlight-go/starlight v0.0.0-20181207205707-b06f321544f3
go: finding golang.org/x/text v0.3.0
go: finding github.com/klauspost/cpuid v1.2.1
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding github.com/Masterminds/goutils v1.1.0
go: finding github.com/Masterminds/semver v1.4.2
go: finding github.com/google/uuid v1.1.1
go: finding github.com/huandu/xstrings v1.2.0
go: finding github.com/cenkalti/backoff v2.1.1+incompatible
go: finding github.com/imdario/mergo v0.3.7
go: finding gopkg.in/square/go-jose.v2 v2.2.2
go: finding github.com/miekg/dns v1.1.3
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
# github.com/caddyserver/caddy/v2/modules/caddyhttp
../../modules/caddyhttp/server.go:186:8: cp.Active undefined (type *caddytls.ConnectionPolicy has no field or method Active)
```
The build in docker works with this PR.
Does a fresh clone and docker build of the `v2` branch work for you? I'd be confused if it does.

**Comment by Henrocker** [comment]
Does the fastcgi branch compile on your setup without this PR?

**Comment by gottwald** [comment]
Yes it does.

**Comment by mholt** [comment]
> I believe you missed that it's not just a nil check.

Are you sure? This is what I see in the diff:

**Comment by mholt** [comment]
My bad. I misread the change.
